### ISSUE TITLE
Magisk installation failed(

### ISSUE THREAD

**Issue by yx7968ww** [BlueArchiveCN/Anti-Harmony-Module#1]
**运行环境**
管理器类型:(magisk/ksu) magisk delta
管理器版本:25.2-delta-5(25200)
Android版本:11
ba版本:1.6.1

**管理器输出及截图**
-Copying zip to temp directory
-Installing install.zip
!Installation failed
![Screenshot_2023-08-05-21-18-18-787_io github huskydg magisk](https://github.com/BlueArchiveCN/Anti-Harmony-Module/assets/110990456/c7dbfad0-cfc1-4c7f-bb58-b84a977fc106)

下载的压缩包是首个正式版（2.0），然后试了下前面的1.1beta是正常刷入的

**Comment by lxdklp** [comment]
我尝试了确实无法复现,不确定是delta兼容性还是什么的
![Screenshot_20230805-221639_面具](https://github.com/BlueArchiveCN/Anti-Harmony-Module/assets/69453767/56d39dfb-5fd0-4e1d-9c5e-ad26429b69f0)
麻烦提供下1.1beta刷入时的完整输出以及把2.0版本的模块作为压缩包解压后的目录也截图一下

因为我看你这个连开头第一句话都没有打印出来应该不是安装脚本问题

**Comment by yx7968ww** [comment]
> 
1.1b
![Screenshot_2023-08-05-22-26-44-569_io github huskydg magisk](https://github.com/BlueArchiveCN/Anti-Harmony-Module/assets/110990456/ee73065f-a5a6-431d-81b4-94fadbb9a4a8)

用ZArchiver Pro直接看的，没解压
![Screenshot_2023-08-05-22-41-35-128_ru zdevs zarchiver pro](https://github.com/BlueArchiveCN/Anti-Harmony-Module/assets/110990456/46cca577-58a6-4a5c-aef4-922a08c731fa)

**Comment by lxdklp** [comment]
你那个是2.0的压缩包嘛,好像文件不太对啊

**Comment by yx7968ww** [comment]
> 你那个是2.0的压缩包嘛,好像文件不太对啊

是的，但我刚刚用电脑重下对比一下发现system文件夹又出现了
平板这边重下了也出现了，刷入正常，也能进入游戏
（一时间不知道是我的问题还是Github的问题）（划掉

**Comment by lxdklp** [comment]
啊这,所以说没问题了嘛,没问题就close了

**Comment by yx7968ww** [comment]
没了，新”特性“另外开吧，开发者辛苦orz
